//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mono_Base_Plate.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mono_Base_Plate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da	As(mm2)	H	SL	D	W	T	e	S	Phi_e	N1	N2	Washer Plate
        ///10	58	0	0	0	0	0	19.6	17	20	15	25	2
        ///12	84.3	0	0	0	0	0	21.9	19	24	20	35	2.5
        ///16	157	320	280	43	70	15	27.7	24	30	25	40	3
        ///20	245	420	380	43	70	15	34.6	30	37	30	50	3
        ///24	324	460	410	68	110	25	41.6	36	44	35	60	4
        ///30	561	570	510	68	110	25	53.1	46	56	45	75	4
        ///36	817	685	615	82	110	25	63.5	55	66	55	90	5
        ///42	1120	800	720	82	150	30	75	65	78	70	110	7
        ///48	1470	920	820	92	150	30	86.5	75	92	80	125	8
        ///56	2030	1070	960	92	200	40	98	85	105	90	145	9
        ///64	2680	1400	1100	92	2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnchorBolts {
            get {
                return ResourceManager.GetString("AnchorBolts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Base_Plate {
            get {
                object obj = ResourceManager.GetObject("Base_Plate", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HEDCO {
            get {
                object obj = ResourceManager.GetObject("HEDCO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Loads {
            get {
                object obj = ResourceManager.GetObject("Loads", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPE100	100.00	55.00	5.70	4.10	7.00	1030.00	11600.00	1710000.00	159000.00	410.00	523.00	34200.00	5782.00	39400.00	9150.00	40.75	12.42
        ///IPE120	120.00	64.00	6.30	4.40	7.00	1320.00	16900.00	3180000.00	277000.00	528.00	672.00	53000.00	8656.00	60700.00	13600.00	49.08	14.49
        ///IPE140	140.00	73.00	6.90	4.70	7.00	1640.00	24000.00	5410000.00	449000.00	658.00	840.00	77286.00	12301.00	88300.00	19200.00	57.44	16.55
        ///IPE160	160.00	82.00	7.40	5.00	9.00	2010.00	35400.00	8690000.00	683000.00	800.00	1011.00	108625.00	16659.00	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Section_I {
            get {
                return ResourceManager.GetString("Section_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P3	8.890	0.5486	14.387068	251.4037811	125.7018905	125.7018905	7.90385516	7.90385516	28.27939045	28.27939045	2.3328	2.3328	2.955866099	2.955866099
        ///P4	11.430	0.6020	20.451572	601.8706414	300.9353207	300.9353207	11.08771976	11.08771976	52.65709899	52.65709899	4.3115	4.3115	3.835952619	3.835952619
        ///P5	14.130	0.6553	27.74188	1265.343534	632.6717669	632.6717669	14.8999702	14.8999702	89.55001718	89.55001718	7.2666	7.2666	4.775526758	4.775526758
        ///P6	16.828	0.7112	35.999928	2339.220612	1169.610306	1169.610306	19.21 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Section_Pipe {
            get {
                return ResourceManager.GetString("Section_Pipe", resourceCulture);
            }
        }
    }
}
