//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base_Plate_Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Base_Plate_Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da	As(mm2)	H	SL	D	W	T	e	S	Phi_e	N1	N2	Washer Plate
        ///10	58	0	0	0	0	0	19.6	17	20	15	25	2
        ///12	84.3	0	0	0	0	0	21.9	19	24	20	35	2.5
        ///16	157	320	280	43	70	15	27.7	24	30	25	40	3
        ///20	245	420	380	43	70	15	34.6	30	37	30	50	3
        ///24	324	460	410	68	110	25	41.6	36	44	35	60	4
        ///30	561	570	510	68	110	25	53.1	46	56	45	75	4
        ///36	817	685	615	82	110	25	63.5	55	66	55	90	5
        ///42	1120	800	720	82	150	30	75	65	78	70	110	7
        ///48	1470	920	820	92	150	30	86.5	75	92	80	125	8
        ///56	2030	1070	960	92	200	40	98	85	105	90	145	9
        ///64	2680	1400	1100	92	2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnchorBolts {
            get {
                return ResourceManager.GetString("AnchorBolts", resourceCulture);
            }
        }
    }
}
